"""add photos column to listings

Revision ID: 583cb9375343
Revises: 656e6abfa50c
Create Date: 2026-05-07 20:01:14.617465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583cb9375343'
down_revision: Union[str, Sequence[str], None] = '656e6abfa50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('type_', sa.String(length=20), nullable=False))
    op.drop_column('listings', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('listings', 'type_')
    # ### end Alembic commands ###
