"""add_coordinates_to_listings

Revision ID: 7b88005cc090
Revises: 8b4c0ac533ce
Create Date: 2026-06-05 21:17:49.342639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b88005cc090'
down_revision: Union[str, Sequence[str], None] = '8b4c0ac533ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_moderation_logs_created_at'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_listing_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_moderator_id'), table_name='moderation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_moderation_logs_moderator_id'), 'moderation_logs', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_listing_id'), 'moderation_logs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_created_at'), 'moderation_logs', ['created_at'], unique=False)
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###
