"""add_unique_constraint_to_translations

Revision ID: 8b4c0ac533ce
Revises: 43379d6663eb
Create Date: 2026-06-05 12:53:32.277928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4c0ac533ce'
down_revision: Union[str, Sequence[str], None] = '43379d6663eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'value',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint('uq_translations_key_locale', 'translations', ['key', 'locale'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_translations_key_locale', 'translations', type_='unique')
    op.alter_column('translations', 'value',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
