"""add chat tables

Revision ID: d1cb5e8af8b1
Revises: 9be58eafa098
Create Date: 2026-06-17 00:32:33.659830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cb5e8af8b1'
down_revision: Union[str, Sequence[str], None] = '9be58eafa098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('latest_message', sa.Text(), nullable=True),
    sa.Column('latest_message_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'owner_id', 'buyer_id', name='uq_conversation')
    )
    op.create_index('idx_conv_buyer_time', 'conversations', ['buyer_id', 'latest_message_time'], unique=False)
    op.create_index('idx_conv_owner_time', 'conversations', ['owner_id', 'latest_message_time'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_conversation_read', 'messages', ['conversation_id', 'is_read'], unique=False)
    op.create_index('idx_msg_conversation_time', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_conversation_time', table_name='messages')
    op.drop_index('idx_msg_conversation_read', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conv_owner_time', table_name='conversations')
    op.drop_index('idx_conv_buyer_time', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
